```{r}
library(dplyr)
library(readr)
library(tibble)
library(stringr)

library(ggplot2)
library(Hmisc)


#masterdf = read.csv("E:/smt/msd_merge/09_24_20_sc35_idrmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge/10-05-20_sc35_pboxmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge/all_sc35_wtmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge2/all_matrin_wtmaster.csv")



#masterdf = read.csv("E:/smt/msd_merge/09_24_20_sc35_idrmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge/10-05-20_sc35_pboxmaster.csv")

#masterdf = read.csv("E:/smt/msd_merge/10-07-20_sc35_slimmaster.csv")

#masterdf = read.csv("E:/smt/msd_merge2/10-30-20_matrin_slim_idrmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge2/11-04-20_matrin_pboxmaster.csv")

```

```{r}

#5ms 7-bin binning of alpha and difco
#for "Brief" versions of masterlist, with "DIFCOLOG_SING" and "ALPHALOG_SING"


masterdf = filter(masterdf, DIFCOLOG_SING < .1)
masterdf = filter(masterdf, DIFCOLOG_SING > 0)
masterdf = filter(masterdf, ALPHALOG_SING > -1)
masterdf = filter(masterdf, ALPHALOG_SING < 2)

binvec = vector(mode = 'character', length = length(masterdf$FRAME))

#first threshold I used was a > or < 0.5

for (a in 1:length(masterdf$FRAME)) 
  {
  if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(2.7/0.01))-12.3)) 
    {
    binvec[a] = 'g'
    }
  else
    {
    if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(1.5/0.01))-3.5))
      {
      binvec[a] = "f"
      }
    else
      {
        if ((masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(5.9/0.01))-6.525)) && (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.485/0.01))-0.3001)))
        {
          binvec[a] = "e"
        }
        else
        {
          if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.011/0.01))+0.2465))
          {
            binvec[a] = "d"
          }
          else
          {
            if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.126/0.01))+0.521))
            {
              binvec[a] = "c"
            }
            else
            {
              if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.077/0.01))+0.9319))
              {
                binvec[a] = "b"
              }
              else
              {
                binvec[a] = "a"
              }
            }
          }
        }
      }
    }
  }



masterdf$BIN = binvec
masterdf = mutate(masterdf, DISTANCE = MEAN_INTENSITY03-MEAN_INTENSITY02)


```


```{r}


#5ms 7-bin binning of alpha and difco
#for full versions of masterlist, with "DIFCOLOG" and "ALPHALOG"


masterdf = filter(masterdf, DIFCOLOG < .1)
masterdf = filter(masterdf, DIFCOLOG > 0)
masterdf = filter(masterdf, ALPHALOG > -1)
masterdf = filter(masterdf, ALPHALOG < 2)

binvec = vector(mode = 'character', length = length(masterdf$FRAME))

#first threshold I used was a > or < 0.5

for (a in 1:length(masterdf$FRAME)) 
  {
  if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(2.7/0.01))-12.3)) 
    {
    binvec[a] = 'g'
    }
  else
    {
    if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(1.5/0.01))-3.5))
      {
      binvec[a] = "f"
      }
    else
      {
        if ((masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(5.9/0.01))-6.525)) && (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.485/0.01))-0.3001)))
        {
          binvec[a] = "e"
        }
        else
        {
          if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.011/0.01))+0.2465))
          {
            binvec[a] = "d"
          }
          else
          {
            if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.126/0.01))+0.521))
            {
              binvec[a] = "c"
            }
            else
            {
              if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.077/0.01))+0.9319))
              {
                binvec[a] = "b"
              }
              else
              {
                binvec[a] = "a"
              }
            }
          }
        }
      }
    }
  }



masterdf$BIN = binvec
masterdf = mutate(masterdf, DISTANCE = MEAN_INTENSITY03-MEAN_INTENSITY02)


```



```{r}
masterdf = select(masterdf, DIFCOLOG, ALPHALOG, CONDITION, CELLCNT, BIN, DISTANCE)
masterdf = arrange(masterdf, CONDITION, BIN)



compiledf = data.frame()

quantvec = c(.01,.02,.03,.04,.05,.06,.07,.08,.09,.10,.11,.12,.13,.14,.15,.16,.17,.18,.19,.20,.21,.22,.23,.24,.25,.26,.27,.28,.29,.30,.31,.32,.33,.34,.35,.36,.37,.38,.39,.40,.41,.42,.43,.44,.45,.46,.47,.48,.49,.50,.51,.52,.53,.54,.55,.56,.57,.58,.59,.60,.61,.62,.63,.64,.65,.66,.67,.68,.69,.70,.71,.72,.73,.74,.75,.76,.77,.78,.79,.80,.81,.82,.83,.84,.85,.86,.87,.88,.89,.90,.91,.92,.93,.94,.95,.96,.97,.98,.99,1)

recompiledf = data.frame(matrix(data = NA, nrow = length(unique(quantvec)), ncol =  ( ((length(unique(masterdf$BIN))) * (length(unique(masterdf$CELLCNT)))) +1)))

recompiledf[1] = quantvec

names(recompiledf)[1] = "QUANTILE"

recompplacehold = 2

for (y in unique(masterdf$CONDITION)) 
{
  for (x in unique(masterdf$BIN))
  {
    tempdf = filter(masterdf, CONDITION == y, BIN == x)
    tempdf = arrange(tempdf, CELLCNT)
    for (w in unique(tempdf$CELLCNT)) 
    {
      temp2df = filter(tempdf, CELLCNT == w)
      
      
      
      z = as.data.frame(quantile(temp2df$DISTANCE, c(.01,.02,.03,.04,.05,.06,.07,.08,.09,.10,.11,.12,.13,.14,.15,.16,.17,.18,.19,.20,.21,.22,.23,.24,.25,.26,.27,.28,.29,.30,.31,.32,.33,.34,.35,.36,.37,.38,.39,.40,.41,.42,.43,.44,.45,.46,.47,.48,.49,.50,.51,.52,.53,.54,.55,.56,.57,.58,.59,.60,.61,.62,.63,.64,.65,.66,.67,.68,.69,.70,.71,.72,.73,.74,.75,.76,.77,.78,.79,.80,.81,.82,.83,.84,.85,.86,.87,.88,.89,.90,.91,.92,.93,.94,.95,.96,.97,.98,.99,1)))
      
      recompiledf[recompplacehold] = z[1]
      names(recompiledf)[recompplacehold] = paste(y,x,w,sep = "_")
      
      z$QUANT = quantvec
      
      z = mutate(z, CONDITION = y, DURATION_BIN = x, CELLCOUNT = w)
      
      
      compiledf = rbind(compiledf, z)
      
      recompplacehold = recompplacehold + 1
      
    }
  }
}

names(compiledf)[1] = "ECDF"


```

```{r}
write.csv(recompiledf, file = 'C:/Users/Tigetmp/Desktop/recompiledf_10-05-20_sc35_pboxmaster')
```

```{r}
library(dplyr)
library(readr)
library(tibble)
library(stringr)

library(ggplot2)
library(Hmisc)


#masterdf = read.csv("E:/smt/msd_merge/09_24_20_sc35_idrmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge/10-05-20_sc35_pboxmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge/all_sc35_wtmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge2/all_matrin_wtmaster.csv")



#masterdf = read.csv("E:/smt/msd_merge/09_24_20_sc35_idrmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge/10-05-20_sc35_pboxmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge/10-07-20_sc35_slimmaster.csv")

#masterdf = read.csv("E:/smt/msd_merge2/10-30-20_matrin_slim_idrmaster.csv")
#masterdf = read.csv("E:/smt/msd_merge2/11-04-20_matrin_pboxmaster.csv")

#masterdf = read.csv("E:/smt/msd_merge2/11-06-20_matrin_118Smaster.csv")
#masterdf = read.csv("E:/smt/msd_merge2/11-10-20_matrin_2Smaster.csv")

masterdf = read.csv("E:/Nikon_Processed_Data/7-21-20/msd_mergemaster.csv")

#5ms 7-bin binning of alpha and difco
#for full versions of masterlist, with "DIFCOLOG" and "ALPHALOG"


masterdf = filter(masterdf, DIFCOLOG < .1)
masterdf = filter(masterdf, DIFCOLOG > 0)
masterdf = filter(masterdf, ALPHALOG > -1)
masterdf = filter(masterdf, ALPHALOG < 2)

binvec = vector(mode = 'character', length = length(masterdf$FRAME))

#first threshold I used was a > or < 0.5

for (a in 1:length(masterdf$FRAME)) 
  {
  if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(2.7/0.01))-12.3)) 
    {
    binvec[a] = 'g'
    }
  else
    {
    if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(1.5/0.01))-3.5))
      {
      binvec[a] = "f"
      }
    else
      {
        if ((masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(5.9/0.01))-6.525)) && (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.485/0.01))-0.3001)))
        {
          binvec[a] = "e"
        }
        else
        {
          if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.011/0.01))+0.2465))
          {
            binvec[a] = "d"
          }
          else
          {
            if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.126/0.01))+0.521))
            {
              binvec[a] = "c"
            }
            else
            {
              if (masterdf$ALPHALOG[a] < ((masterdf$DIFCOLOG[a]*(0.077/0.01))+0.9319))
              {
                binvec[a] = "b"
              }
              else
              {
                binvec[a] = "a"
              }
            }
          }
        }
      }
    }
  }



masterdf$BIN = binvec
masterdf = mutate(masterdf, DISTANCE = MEAN_INTENSITY03-MEAN_INTENSITY02)


masterdf = select(masterdf, DIFCOLOG, ALPHALOG, CONDITION, CELLCNT, BIN, DISTANCE)
masterdf = arrange(masterdf, CONDITION, BIN)



compiledf = data.frame()

quantvec = c(.01,.02,.03,.04,.05,.06,.07,.08,.09,.10,.11,.12,.13,.14,.15,.16,.17,.18,.19,.20,.21,.22,.23,.24,.25,.26,.27,.28,.29,.30,.31,.32,.33,.34,.35,.36,.37,.38,.39,.40,.41,.42,.43,.44,.45,.46,.47,.48,.49,.50,.51,.52,.53,.54,.55,.56,.57,.58,.59,.60,.61,.62,.63,.64,.65,.66,.67,.68,.69,.70,.71,.72,.73,.74,.75,.76,.77,.78,.79,.80,.81,.82,.83,.84,.85,.86,.87,.88,.89,.90,.91,.92,.93,.94,.95,.96,.97,.98,.99,1)

recompiledf = data.frame(matrix(data = NA, nrow = length(unique(quantvec)), ncol =  ( ((length(unique(masterdf$BIN))) * (length(unique(masterdf$CELLCNT)))) +1)))

recompiledf[1] = quantvec

names(recompiledf)[1] = "QUANTILE"

recompplacehold = 2

for (y in unique(masterdf$CONDITION)) 
{
  for (x in unique(masterdf$BIN))
  {
    tempdf = filter(masterdf, CONDITION == y, BIN == x)
    tempdf = arrange(tempdf, CELLCNT)
    for (w in unique(tempdf$CELLCNT)) 
    {
      temp2df = filter(tempdf, CELLCNT == w)
      
      
      
      z = as.data.frame(quantile(temp2df$DISTANCE, c(.01,.02,.03,.04,.05,.06,.07,.08,.09,.10,.11,.12,.13,.14,.15,.16,.17,.18,.19,.20,.21,.22,.23,.24,.25,.26,.27,.28,.29,.30,.31,.32,.33,.34,.35,.36,.37,.38,.39,.40,.41,.42,.43,.44,.45,.46,.47,.48,.49,.50,.51,.52,.53,.54,.55,.56,.57,.58,.59,.60,.61,.62,.63,.64,.65,.66,.67,.68,.69,.70,.71,.72,.73,.74,.75,.76,.77,.78,.79,.80,.81,.82,.83,.84,.85,.86,.87,.88,.89,.90,.91,.92,.93,.94,.95,.96,.97,.98,.99,1)))
      
      recompiledf[recompplacehold] = z[1]
      names(recompiledf)[recompplacehold] = paste(y,x,w,sep = "_")
      
      z$QUANT = quantvec
      
      z = mutate(z, CONDITION = y, DURATION_BIN = x, CELLCOUNT = w)
      
      
      compiledf = rbind(compiledf, z)
      
      recompplacehold = recompplacehold + 1
      
    }
  }
}

names(compiledf)[1] = "ECDF"

write.csv(recompiledf, file = 'C:/Users/Tigetmp/Desktop/recompiledf_7-21-20_pboxslimmaster')

```



```{r}

#bin the "brief" masterfiles into the 7 bins and save these newly binned brief masterfiles

library(dplyr)
library(readr)
library(tibble)
library(stringr)

library(ggplot2)
library(Hmisc)

#masterdf = read.csv("E:/smt/msd_merge/09_24_20_sc35_idrmaster_brief.csv")
#masterdf = read.csv("E:/smt/msd_merge/10-05-20_sc35_pboxmaster_brief.csv")
#masterdf = read.csv("E:/smt/msd_merge/10-07-20_sc35_slimmaster_brief.csv")
#masterdf = read.csv("E:/smt/msd_merge2/10-30-20_matrin_slim_idrmaster_brief.csv")
#masterdf = read.csv("E:/smt/msd_merge2/11-04-20_matrin_pboxmaster_brief.csv")
#masterdf = read.csv("E:/smt/msd_merge2/11-06-20_matrin_118Smaster_brief.csv")
#masterdf = read.csv("E:/smt/msd_merge2/11-10-20_matrin_2Smaster_brief.csv")
#masterdf = read.csv("E:/Nikon_Processed_Data/7-21-20/msd_mergemaster_brief.csv")
#masterdf = read.csv("E:/smt/new_msd_mergemaster_brief.csv")
masterdf = read.csv("C:/Users/Tigetmp/Desktop/temp/smt/msd_merge_pg_d150170_1000framelimmaster_brief.csv")



#5ms 7-bin binning of alpha and difco
#for "Brief" versions of masterlist, with "DIFCOLOG_SING" and "ALPHALOG_SING"


masterdf = filter(masterdf, DIFCOLOG_SING < .1)
masterdf = filter(masterdf, DIFCOLOG_SING > 0)
masterdf = filter(masterdf, ALPHALOG_SING > -1)
masterdf = filter(masterdf, ALPHALOG_SING < 2)

binvec = vector(mode = 'character', length = length(masterdf$FRAME))

#first threshold I used was a > or < 0.5

for (a in 1:length(masterdf$FRAME)) 
  {
  if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(2.7/0.01))-12.3)) 
    {
    binvec[a] = 'g'
    }
  else
    {
    if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(1.5/0.01))-3.5))
      {
      binvec[a] = "f"
      }
    else
      {
        if ((masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(5.9/0.01))-6.525)) && (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.485/0.01))-0.3001)))
        {
          binvec[a] = "e"
        }
        else
        {
          if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.011/0.01))+0.2465))
          {
            binvec[a] = "d"
          }
          else
          {
            if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.126/0.01))+0.521))
            {
              binvec[a] = "c"
            }
            else
            {
              if (masterdf$ALPHALOG_SING[a] < ((masterdf$DIFCOLOG_SING[a]*(0.077/0.01))+0.9319))
              {
                binvec[a] = "b"
              }
              else
              {
                binvec[a] = "a"
              }
            }
          }
        }
      }
    }
  }



masterdf$BIN = binvec
masterdf = mutate(masterdf, DISTANCE = MEAN_INTENSITY03-MEAN_INTENSITY02)

#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_09_24_20_sc35_idrmaster_brief.csv')
#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_10-05-20_sc35_pboxmaster_brief.csv')
#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_10-07-20_sc35_slimmaster_brief.csv')
#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_10-30-20_matrin_slim_idrmaster_brief.csv')
#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_11-04-20_matrin_pboxmaster_brief.csv')
#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_11-06-20_matrin_118Smaster_brief.csv')
#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_7-21-20_pboxslimmaster_brief.csv')
#write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/bin7_5-21_and_6-18-21_PG_newIDRS_master_brief.csv')
write.csv(masterdf, file = 'C:/Users/Tigetmp/Desktop/temp/msd_merge_pg_d150170_1000framelimmaster_brief_clustered.csv')



```





