```{r}
###script for calculating averaged rose (converted to 180 degrees) and average displacements for track, using the msd_merge output from the 8-23-2021 version of the statscalc that doesn't have this function incorporated into it.  This version of statscalc used for this script DOES have the duration and radius of confinement calcs in it, but I don't think this script is reliant upon those features in any way.  But it could, if I get some errors from running this using that output as this script's input.  
###these averages only include displacements and rose values for immediately subsequent frames.  Spots where the track skips a frame are skipped.

library(dplyr)
library(readr)
library(tibble)
library(stringr)



testdf = read_csv('C:/Users/Tigetmp/Desktop/newdftest.csv')

trackstart_temp_pos = 1

framecount = 0
dispvec = vector()
rosevec = vector()

avedisp_vector = rep(0, length(testdf$TRACK_ID))
averose_vector = rep(0, length(testdf$TRACK_ID))

for (aa in 2:length(testdf$TRACK_ID)) {
  if (testdf$TRACK_ID[aa] != testdf$TRACK_ID[(aa-1)]) {
    if (framecount > 0) {
      avedisp_vector[trackstart_temp_pos] = sum(dispvec)/framecount
      averose_vector[trackstart_temp_pos] = sum(rosevec)/framecount
    }
    
    
    trackstart_temp_pos = aa
    framecount = 0
    dispvec = vector()
    rosevec = vector()
    
    
  }
  else{
    if (testdf$FRAME[aa] == (testdf$FRAME[aa-1] + 1)) {
      
      dispvec = c(dispvec,testdf$DISP1[(aa-1)])
      if (testdf$DEGREENORM[(aa-1)] > 180) {
        rosevec = c(rosevec, ((testdf$DEGREENORM[(aa-1)]-360) * -1))
      }
      else{
        rosevec = c(rosevec, testdf$DEGREENORM[(aa-1)])
      }
      framecount = framecount + 1
      
    }
    
  }
  
}

avedisp_vector[trackstart_temp_pos] = sum(dispvec)/framecount
averose_vector[trackstart_temp_pos] = sum(rosevec)/framecount


newdf = testdf
newdf$AVERAGE_DISPLACEMENT = avedisp_vector
newdf$AVERAGE_ROSE = averose_vector
```

```{r}
#script for batch processing of msd_merge folder from statscalc output described in the above script's comment section
#output will then be place into a folder named 'msd_merge_2'

library(dplyr)
library(readr)
library(tibble)
library(stringr)

#parentdir = 'F:/6-5-20_Nikon_smt_sc35_er/yul/'
#parentdir = 'C:/Users/Tigetmp/Desktop/test/all_e2/'
#parentdir = 'F:/6-24-20/'
#parentdir = 'C:/temp/'
#parentdir = 'E:/7-29-21_DNA_fast_smt-like/'
#parentdir = 'C:/User/Tom/smt/'
#parentdir = 'E:/smt/newtif_spots/'
#parentdir = 'C:/User/Tom/drift_correction/minus_e2/zproj/alpha_difco_calc/'
#parentdir = 'C:/User/Tom/fast_dna_movies_8_27_8_30_9_22/rscripts/'
#parentdir = 'D:/Nikon_Processed_Data/6-29-20/'
#parentdir = 'D:/Nikon_Processed_Data/6-24-20/'
#parentdir = 'E:/smt_reprocess_12-9-21/'
#parentdir = 'E:/NIKON/process_031022_031522_medbrd4/'
parentdir = 'E:/6-6-23-ER_flavo/'


spotslistfull = list.files(str_c(parentdir,'msd_merge\\'), full.names = TRUE)

spotslistshort = list.files(str_c(parentdir,'msd_merge\\'), full.names = FALSE)




for (i in 1:length(spotslistfull)) 
{
  
testdf = read_csv(spotslistfull[i])

trackstart_temp_pos = 1

framecount = 0
dispvec = vector()
rosevec = vector()

avedisp_vector = rep(0, length(testdf$TRACK_ID))
averose_vector = rep(0, length(testdf$TRACK_ID))

for (aa in 2:length(testdf$TRACK_ID)) {
  if (testdf$TRACK_ID[aa] != testdf$TRACK_ID[(aa-1)]) {
    if (framecount > 0) {
      avedisp_vector[trackstart_temp_pos] = sum(dispvec)/framecount
      averose_vector[trackstart_temp_pos] = sum(rosevec)/framecount
    }
    
    
    trackstart_temp_pos = aa
    framecount = 0
    dispvec = vector()
    rosevec = vector()
    
    
  }
  else{
    if (testdf$FRAME[aa] == (testdf$FRAME[aa-1] + 1)) {
      
      dispvec = c(dispvec,testdf$DISP1[(aa-1)])
      if (testdf$DEGREENORM[(aa-1)] > 180) {
        rosevec = c(rosevec, ((testdf$DEGREENORM[(aa-1)]-360) * -1))
      }
      else{
        rosevec = c(rosevec, testdf$DEGREENORM[(aa-1)])
      }
      framecount = framecount + 1
      
    }
    
  }
  
}

avedisp_vector[trackstart_temp_pos] = sum(dispvec)/framecount
averose_vector[trackstart_temp_pos] = sum(rosevec)/framecount


newdf = testdf
newdf$AVERAGE_DISPLACEMENT = avedisp_vector
newdf$AVERAGE_ROSE = averose_vector

write.csv(newdf, file = str_c(parentdir,'msd_merge_2/',substr(spotslistshort[i],1,(str_length(spotslistshort[i])-4)),'.csv'))

}
```

